// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNy8aL6w-dLw8sKxK3Zj8kfSzIIKo9bSI',
    appId: '1:52291874613:web:b0f7283157e5a8081f667c',
    messagingSenderId: '52291874613',
    projectId: 'stouchi-8c2ba',
    authDomain: 'stouchi-8c2ba.firebaseapp.com',
    storageBucket: 'stouchi-8c2ba.appspot.com',
    measurementId: 'G-VXE8KK0GT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3EMgFf2CD3Oc_ASthy8qf-QxGCwRPXEQ',
    appId: '1:52291874613:android:f15e59d4445e50311f667c',
    messagingSenderId: '52291874613',
    projectId: 'stouchi-8c2ba',
    storageBucket: 'stouchi-8c2ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWbPuslTH6KwxGANm3UccjIUHJuebx5k0',
    appId: '1:52291874613:ios:248c9b3e1e6f1aaf1f667c',
    messagingSenderId: '52291874613',
    projectId: 'stouchi-8c2ba',
    storageBucket: 'stouchi-8c2ba.appspot.com',
    iosBundleId: 'com.stouchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWbPuslTH6KwxGANm3UccjIUHJuebx5k0',
    appId: '1:52291874613:ios:23922d653344a7251f667c',
    messagingSenderId: '52291874613',
    projectId: 'stouchi-8c2ba',
    storageBucket: 'stouchi-8c2ba.appspot.com',
    iosBundleId: 'com.stouchi.RunnerTests',
  );
}
